### ISSUE TITLE
Can't get imba to compile

### ISSUE THREAD

**Issue by perfaram** [somebee/todomvc-meteor-imba#1]
Hi !
I followed the instructions on the Readme, but I'm running into issues :
Running `meteor` after a clean clone from this repo, and without running imba, works as expected. However, running `imba watch src/ -o app/` breaks it all by outputting JS files only... any idea ?

EDIT : Trying to replace the "stock" (taken from this repo) JS files by the imba-produced ones doesn't work, either.

**Comment by somebee** [comment]
Looking into it now. Thanks for reporting

**Comment by somebee** [comment]
Update to the latest version of Imba now. Could you pull and see if it works now? When running imba watch, make sure that you have the latest version installed `imba --version` should return 0.14.3.

**Comment by perfaram** [comment]
It works now, thx ! BTW I already had Imba’s last version.

-- 
Perceval Faramaz

On 23 janvier 2016 at 14:24:14, Sindre Aarsaether (notifications@github.com) wrote:

Update to the latest version of Imba now. Could you pull and see if it works now? When running imba watch, make sure that you have the latest version installed imba --version should return 0.14.3.

**Comment by perfaram** [comment]
It works now, thx ! BTW I already had Imba’s last version.

-- 
Perceval Faramaz

On 23 janvier 2016 at 14:24:14, Sindre Aarsaether (notifications@github.com) wrote:

Update to the latest version of Imba now. Could you pull and see if it works now? When running imba watch, make sure that you have the latest version installed imba --version should return 0.14.3.
